version: 2

project_name: binget

builds:
  - builder: zig
    flags:
      - -Doptimize=ReleaseSafe
    targets:
      - x86_64-linux-gnu
      - x86_64-windows-gnu
      - aarch64-linux-gnu
      - aarch64-macos-none
      - x86_64-macos-none

archives:
  - formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}-{{ .Os }}-{{ if eq .Arch "x86_64" }}amd64{{ else if eq .Arch "amd64" }}amd64{{ else if eq .Arch "aarch64" }}arm64{{ else if eq .Arch "arm64" }}arm64{{ else }}{{ .Arch }}{{ end }}-v{{ .Version }}
    format_overrides:
      - goos: windows
        formats:
          - zip

nfpms:
  - file_name_template: >-
      {{ .ProjectName }}-{{ .Os }}-{{ if eq .Arch "x86_64" }}amd64{{ else if eq .Arch "amd64" }}amd64{{ else if eq .Arch "aarch64" }}arm64{{ else if eq .Arch "arm64" }}arm64{{ else }}{{ .Arch }}{{ end }}-v{{ .Version }}
    formats:
      - deb
      - rpm
      - apk
    maintainer: "Binget Authors <email@example.com>"
    description: "Binget package manager"
    bindir: /usr/bin

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
